config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: :show do
    collection do
      get 'feed'
    end
    member do
      post 'follow'
      delete 'unfollow'
      get 'following'
      get "followers"
    end
  end
  resources :posts do
    resources :comments, only: [:index, :create, :destroy]
    collection do
      get 'liked'
    end
    member do
      post 'like'
      delete 'unlike'
    end

  end
  root 'welcome#index'

  get 'search' => 'search#index'
  get 'hashtag/:id' => 'hashtag#index', as: "hashtag"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post, counter_cache: true
  belongs_to :user

  validates :post, presence: true
  validates :user, presence: true
  validates :content, length: {minimum: 1, maximum: 100}
  self.per_page = 12
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @post = Post.find(params[:post_id])
    @comments = @post.comments.paginate(page: params[:page])
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = current_user.comments.build(comment_params)
    @comment.post = @post
    respond_to do |format|
      if @comment.save
        format.html {redirect_to @post, notice: "Comment created."}
        format.js
      else
        format.html do
          flash[:danger] = @comment.errors.full_messages.first
          redirect_to @post
        end
        format.js
      end
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = current_user.comments.find(params[:id]).delete
    respond_to do |format|
      format.html {redirect_to @post, notice: "Your comment was deleted."}
      format.js
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
.comment
	= link_to comment.user.username, user_path(comment.user)
	= comment.content
	- if user_signed_in? && current_user == comment.user
		.pull-right
			= link_to post_comment_path(comment.post, comment), method: :delete, remote: true, class: "delete-comment label label-danger" do
				%span.glyphicon.glyphicon-trash

app/views/comments/create.js.haml
- if @comment.errors.any?
  $("#new_comment .form-group").addClass("has-error")
  $("#new_comment .form-group").parent().append("<div class='comment-error text-danger'>#{@comment.errors.full_messages.first}</div>")
- else
  $("#new_comment .form-group").removeClass("has-error")
  $(".comment-error").remove()
  $("#{j render @comment}").appendTo(".comments-content").hide().fadeIn(1400)
  $("#comment_content").val('')

app/views/comments/destroy.js.haml
$(".comments a[href='#{post_comment_path(@comment.post, @comment)}']").parent().parent().fadeOut("slow", function(){$(this).remove()})

app/views/comments/index.js.haml
$(".comments-content").prepend("#{j render @comments}")
- if @comments.next_page
  $(".comment-pagination").html("#{j link_to "load more comments", post_comments_path(@post, page: @comments.next_page), remote: true}")
- else
  $(".comment-pagination").remove()