config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: :show do
    collection do
      get 'feed'
    end
    member do
      post 'follow'
      delete 'unfollow'
      get 'following'
      get "followers"
    end
  end
  resources :posts do
    resources :comments, only: [:index, :create, :destroy]
    collection do
      get 'liked'
    end
    member do
      post 'like'
      delete 'unlike'
    end

  end
  root 'welcome#index'

  get 'search' => 'search#index'
  get 'hashtag/:id' => 'hashtag#index', as: "hashtag"

end

app/models/user.rb
class User < ActiveRecord::Base

  extend FriendlyId
  friendly_id :username, use: :slugged
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, length: {minimum: 2, maximum: 40}, uniqueness: true, format: { with: /\A[a-zA-Z0-9_-]+\Z/ }
  validates :bio, length: {maximum: 200}
  has_attached_file :avatar, styles: { medium: "300x300#", thumb: "100x100#" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates_with AttachmentPresenceValidator, attributes: :avatar
  validates_with AttachmentSizeValidator, attributes: :avatar, less_than: 4.megabytes

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :following_relationships, foreign_key: :follower_id, dependent: :destroy
  has_many :followers, through: :followed_relationships
  has_many :followed_relationships, foreign_key: :followed_id, class_name: "FollowingRelationship", dependent: :destroy
  has_many :followed_users, through: :following_relationships, source: :followed

  def likes?(post)
    !!Like.find_by(post: post, user: self)
  end

  def follows?(user)
    return true if self.following_relationships.find_by_followed_id(user.id)
    false
  end

  def feed
    followed_user_ids = "SELECT followed_id FROM following_relationships WHERE follower_id = ?"
    Post.where("user_id IN (#{followed_user_ids})", self.id).order("created_at DESC")
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :find_user, except: [:feed]

  def show
    @posts = @user.posts.order("created_at DESC").paginate(:page => params[:page], :per_page => 12)
  end

  def follow
    rel = current_user.following_relationships.build(followed_id: @user.id)
    if rel.save
      respond_to do |format|
        format.html { redirect_to @user, notice: "You are now following #{@user.username}." }
        format.js
      end
    else
      respond_to do |format|
        format.html do
          flash[:danger] = "You already follow this user."
          redirect_to @user
        end
        format.js
      end
    end
  end

  def unfollow
    current_user.following_relationships.find_by_followed_id(@user.id).delete
    respond_to do |format|
      format.html {redirect_to @user, notice: "You are not following #{@user.username} anymore."}
      format.js { render "follow"}
    end
  end

  def following
    @users = @user.followed_users.paginate(page: params[:page], per_page: 15)
  end

  def followers
    @users = @user.followers.paginate(page: params[:page], per_page: 15)
  end

  def feed
    @posts = current_user.feed.paginate(page: params[:page], per_page: 12)
  end

  private

  def find_user
    @user = User.friendly.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.haml
%li.list-group-item
  .media
    .media-left= link_to image_tag(user.avatar.url(:thumb), class: "img-responsive"), user
    .media-body
      = link_to user do
        %h3.media-heading= user.username
        .media-desc= user.bio
    .media-right
      = render "shared/follow_button", user: user

app/views/users/feed.html.haml
%h2
  %span.label.label-primary Your feed:
.row
  .posts
    = render @posts
%br

- if @posts.next_page
  .row.text-center
    .pagination
      = link_to "Load more", feed_users_path(page: @posts.next_page), remote: true, class: "btn btn-lg btn-primary"
= render "shared/post_modal"

app/views/users/feed.js.haml
$(".posts").append("#{j render @posts}")
- if @posts.next_page
  $(".pagination").html("#{j link_to "Load more", feed_users_path(page: @posts.next_page), remote: true, class: 'btn btn-lg btn-primary'}")
- else
  $(".pagination").hide()

app/views/users/follow.js.haml
:plain
  $(".follow-button-user-#{@user.slug}").fadeOut("slow", function() {
    $(".follow-button-user-#{@user.slug}").html("#{j render "shared/follow_button", user: @user}").fadeIn("slow")
  })
  $(".followers").html("#{j pluralize(@user.followers.count, "follower")}")

app/views/users/followers.html.haml
%h2
  %span.label.label-primary= "followers of #{@user.username}:"
%ul.users.list-group
  - if @users.count > 0
    = render @users
  - else
    %h3 Nobody yet.
- if @users.next_page
  .row
    .col-md-4.col-md-offset-4.text-center
      .pagination= link_to "Load more", followers_user_path(@user, page: @users.next_page), remote: true, class: "btn btn-lg btn-primary"

app/views/users/followers.js.haml
$(".users").append("#{j render @users}")
- if @users.next_page
  $(".pagination").html("#{j link_to "Load more", followers_user_path(@user, page: @posts.next_page), remote: true, class: 'btn btn-lg btn-primary'}")
- else
  $(".pagination").hide()

app/views/users/following.html.haml
%h2
  %span.label.label-primary= "#{@user.username} is following:"
%ul.list-group.users
  - if @users.count > 0
    = render @users
  - else
    %h3 Nobody yet.
- if @users.next_page
  .row
    .col-md-4.col-md-offset-4.text-center
      .pagination= link_to "Load more", following_user_path(@user, page: @users.next_page), remote: true, class: "btn btn-lg btn-primary"

app/views/users/following.js.haml
$(".users").append("#{j render @users}")
- if @users.next_page
  $(".pagination").html("#{j link_to "Load more", following_user_path(@user, page: @posts.next_page), remote: true, class: 'btn btn-lg btn-primary'}")
- else
  $(".pagination").hide()

app/views/users/show.html.haml
.row
  .col-md-4.col-xs-4= image_tag(@user.avatar.url(:medium), class: "img-responsive circular center-block")
  .col-md-8.col-xs-8
    %br
    %h2
      = @user.username
      = render "shared/follow_button", user: @user
    %p
      %i.h5= @user.bio
    %br
    .row
      .col-md-4.col-xs-4.h4= pluralize(@user.posts.count, "post")
      .col-md-4.col-xs-4.h4= link_to pluralize(@user.followers.count, "follower"), followers_user_path(@user), class: "followers"
      .col-md-4.col-xs-4.h4= link_to "#{@user.following_relationships.count} following", following_user_path(@user), class: "following"
%br
.row
  .posts
    = render @posts
%br
- if @posts.next_page
  .row
    .col-md-4.col-md-offset-4.text-center
      .pagination= link_to "Load more", user_path(@user, page: @posts.next_page), remote: true, class: "btn btn-lg btn-primary"
%br
= render "shared/post_modal"

app/views/users/show.js.haml
$(".posts").append("#{j render @posts}")
- if @posts.next_page
  $(".pagination").html("#{j link_to "Load more", user_path(@user, page: @posts.next_page), remote: true, class: 'btn btn-lg btn-primary'}")
- else
  $(".pagination").hide()