config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: :show do
    collection do
      get 'feed'
    end
    member do
      post 'follow'
      delete 'unfollow'
      get 'following'
      get "followers"
    end
  end
  resources :posts do
    resources :comments, only: [:index, :create, :destroy]
    collection do
      get 'liked'
    end
    member do
      post 'like'
      delete 'unlike'
    end

  end
  root 'welcome#index'

  get 'search' => 'search#index'
  get 'hashtag/:id' => 'hashtag#index', as: "hashtag"

end

app/views/shared/_follow_button.html.haml
%span{:class => "follow-button-user-#{user.slug}"}
  - if user_signed_in? && current_user.follows?(user)
    = link_to unfollow_user_path(user), method: :delete, remote: true, class: "btn btn-success", data: {confirm: "Are you sure?"} do
      %span.glyphicon.glyphicon-ok
      Following
  - else
    = link_to follow_user_path(user), method: :post, remote: true, class: "btn btn-primary" do
      %span.glyphicon.glyphicon-user
      Follow

app/views/shared/_like_button.html.haml
- if current_user.likes?(@post)
  = button_to unlike_post_path(@post), method: :delete, remote: true, class: "btn btn-primary" do
    %span.glyphicon.glyphicon-heart-empty
    Unlike

- else
  = button_to like_post_path(@post), remote: true, class: "btn btn-primary" do
    %span.glyphicon.glyphicon-heart
    Like

app/views/shared/_post_modal.html.haml
#post-modal.modal.fade{tabindex: "-1", role: "dialog"}