config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: :show do
    collection do
      get 'feed'
    end
    member do
      post 'follow'
      delete 'unfollow'
      get 'following'
      get "followers"
    end
  end
  resources :posts do
    resources :comments, only: [:index, :create, :destroy]
    collection do
      get 'liked'
    end
    member do
      post 'like'
      delete 'unlike'
    end

  end
  root 'welcome#index'

  get 'search' => 'search#index'
  get 'hashtag/:id' => 'hashtag#index', as: "hashtag"

end

app/views/layouts/_footer.html.haml
%footer.clearfix
  %h5
    = link_to "My Github", "https://github.com/LOSDev?tab=repositories", target: '_blank'
    .pull-right &copy; 2016 LOSDEV
  %h5

app/views/layouts/_login_modal.html.haml
#login-modal.modal.fade{tabindex: "-1", role: "dialog"}
  .modal-dialog.modal-sm
    .modal-content
      .modal-header
        %h4.text-center Log in
      = simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f|
        .modal-body
          .form-inputs
            = f.input :email, required: true, autofocus: true
            = f.input :password, required: true
            = f.input :remember_me, as: :boolean if devise_mapping.rememberable?
          .form-actions
        .modal-footer= f.button :submit, "Log in", class: "btn btn-primary btn-block"

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default
  .container-fluid.col-md-8.col-md-offset-2.col-xs-12
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Instaclone", root_path, class: "navbar-brand"
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li &nbsp;&nbsp;&nbsp;&nbsp;
        .navbar-form.navbar-left
          .form-group.has-feedback
            = search_field_tag :search_term, nil, placeholder: "Search", class: "form-control", size: 23
            %span.glyphicon.glyphicon-search.form-control-feedback

      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          = link_to new_post_path, class: "btn btn-primary navbar-btn navbar-left" do
            %span.glyphicon.glyphicon-picture
            New Post

          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              %span.glyphicon.glyphicon-menu-hamburger
              = current_user.username
              %span.caret
            %ul.dropdown-menu
              %li
                = link_to user_path(current_user) do
                  %span.glyphicon.glyphicon-user
                  My Profile
              %li
                = link_to feed_users_path do
                  %span.glyphicon.glyphicon-list-alt
                  My Feed
              %li
                = link_to liked_posts_path do
                  %span.badge.likes= current_user.likes.count
                  Liked Posts
              %li.divider
              %li
                = link_to edit_user_registration_path do
                  %span.glyphicon.glyphicon-cog
                  Account Settings
              %li
                = link_to destroy_user_session_path, method: :delete do
                  %span.glyphicon.glyphicon-log-out
                  Log out

        - else
          %li= link_to "Register", new_user_registration_path
          %li= link_to "Log in", new_user_session_path, class: "login-button"
    / /.navbar-collapse
  / /.container-fluid

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title InstagramCopy
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render "layouts/navbar"
    .flash
      - flash.each do |name, msg|
        .text-center= content_tag(:div, msg, class: "alert alert-#{name == "notice" ? "info" : name}")
    .col-md-8.col-md-offset-2
      = yield
    .col-md-8.col-md-offset-2
      %hr
      = render "layouts/footer"
      %br
    = render "layouts/login_modal" unless user_signed_in?